---
abstract: 'RESTful interface to Factual.com, using Spore'
author:
  - 'Andrew Grangaard <spazm@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-HTTP-Factual
requires:
  Moose: 0
  Net::HTTP::Spore: 0
  strict: 0
  warnings: 0
resources:
  repository: http://github.com/spazm/Net-HTTP-Factual.git
version: 0.122480
